color = "Always"
fn_single_line = true
force_multiline_blocks = false
format_strings = true
indent_style = "Visual"
normalize_comments = true
normalize_doc_attributes = true
wrap_comments = true
width_heuristics = "Max"